import { Buffer } from "node:buffer";
import { expect, test } from "@playwright/test";

const baseURL = process.env.E2E_BASE_URL ?? "http://127.0.0.1:8080";
test.use({ baseURL });

test("build and edit a multi-collector lab with devices and uploaded replay", async ({ page, request }) => {
  const name = `Browser log lab ${Date.now()}`;
  const datasetName = `${name}.ndjson`;
  await page.goto("/lab");
  await page.getByLabel("Name", { exact: true }).fill(name);
  await page.getByLabel("Find a source").fill("domain");
  await page.getByLabel("Source", { exact: true }).selectOption("windows-dc");
  await page.getByLabel("Logon Failure", { exact: true }).check();
  await page.getByLabel("User pool (one name per line)").fill("alice\nbob");
  await page.getByLabel("Correlated incident preset").selectOption("password_spray");
  await page.getByRole("button", { name: "Add device" }).click();
  await page.getByLabel("Device 1 hostname").fill("dc01.browser.test");
  await page.getByLabel("Device 1 IP").fill("192.0.2.55");
  await page.getByLabel("Collector 1 host").fill("127.0.0.1");
  await page.getByRole("button", { name: "Add collector" }).click();
  await page.getByLabel("Collector 2 transport").selectOption("http_webhook");
  await page.locator('input[type="url"]').fill("http://127.0.0.1:9000/lab");
  await page.getByLabel("Collector 2 payload format").selectOption("json");
  await page.getByLabel("Upload log dataset").setInputFiles({ name: datasetName, mimeType: "application/x-ndjson", buffer: Buffer.from('{"TimeGenerated":"2020-01-01T00:00:00Z","customDate":"2020-01-01T00:00:00Z","msg":"browser lab"}\n') });
  await expect(page.getByRole("option", { name: `${datasetName} (1 records)` })).toBeAttached();
  await page.getByLabel("Loop dataset").check();
  await page.getByLabel("Rewrite recognized timestamps to current time").check();
  await page.getByRole("button", { name: "Preview dataset" }).click();
  await expect(page.locator("pre")).toContainText('"unknown_timestamp_fields"');
  await expect(page.locator("pre")).toContainText('"customDate"');
  await expect(page.locator("input:invalid")).toHaveCount(0);
  await page.getByRole("button", { name: "Create lab", exact: true }).click();
  await expect(page).toHaveURL(/\/simulations\/[a-f0-9-]+$/);
  const id = page.url().split("/").at(-1)!;
  const simulation = await (await request.get(`/api/v1/simulations/${id}`)).json();
  expect(simulation.targets).toHaveLength(2);
  expect(simulation.schedule.user_pool).toEqual(["alice", "bob"]);
  expect(simulation.schedule.incident_preset).toBe("password_spray");
  expect(simulation.devices[0].hostname).toBe("dc01.browser.test");
  expect(simulation.replay_config.loop).toBe(true);
  await expect(page.getByRole("heading", { name: "Collector delivery" })).toBeVisible();
  await page.getByRole("link", { name: "Collectors & replay" }).click();
  await expect(page.getByLabel("Collector 2 transport")).toHaveValue("http_webhook");
  await page.getByRole("button", { name: "Preview saved wire bytes" }).first().click();
  await expect(page.locator("pre")).toContainText('"wire_base64"');
  await page.getByLabel("Collector 1 name").fill("Renamed primary");
  await page.getByRole("button", { name: "Save lab" }).click();
  await expect(page).toHaveURL(/\/simulations\/[a-f0-9-]+$/);
  const exported = await (await request.get(`/api/v1/simulations/${id}/export`)).json();
  expect(exported.format_version).toBe("3.0");
  expect(exported.simulation.targets[0].name).toBe("Renamed primary");
  expect(exported.simulation.targets).toHaveLength(2);
  await request.delete(`/api/v1/simulations/${id}`);
  await request.delete(`/api/v1/datasets/${simulation.replay_config.dataset_id}`);
});
